### ISSUE TITLE
`Filter must not be larger than the input` error

### ISSUE THREAD

**Issue by lunardog** [rykov8/ssd_keras#2]
When I try the notebook, I get this error message:
```
ValueError: Filter must not be larger than the input: Filter: (3, 3) Input: (1, 1)
```
in this line:
```
    x = Convolution2D(24, 3, 3, border_mode='same',
                      name='pool6_mbox_loc')(net['pool6'])
```

It passes when I change it to:
```
    x = Convolution2D(24, 1, 1, border_mode='same',
                      name='pool6_mbox_loc')(net['pool6'])
```
but then loading the weights fails.

`pool6` is indeed reshaped to `(1, 1, 256)`, so what can I do to fit the `(3, 3)`  convolution?

**Comment by rykov8** [comment]
@lunardog do you use Tensorflow backend? What versions of Keras and Tensorflow do you use? The thing is, that I don't have this error. I believe, that the line
``` Python
x = Convolution2D(24, 3, 3, border_mode='same',
                  name='pool6_mbox_loc')(net['pool6'])
```
actually should add paddings to the input and then apply convolution. So, my suggestion for you is the following. Change the block `# Prediction from pool6` to the code below:
``` Python
net['pool6_pad'] = ZeroPadding2D()(net['pool6'])
x = Convolution2D(24, 3, 3, border_mode='valid',
                  name='pool6_mbox_loc')(net['pool6_pad'])
net['pool6_mbox_loc'] = x
flatten = Flatten(name='pool6_mbox_loc_flat')
net['pool6_mbox_loc_flat'] = flatten(net['pool6_mbox_loc'])
x = Convolution2D(126, 3, 3, border_mode='valid',
                  name='pool6_mbox_conf')(net['pool6_pad'])
net['pool6_mbox_conf'] = x
flatten = Flatten(name='pool6_mbox_conf_flat')
net['pool6_mbox_conf_flat'] = flatten(net['pool6_mbox_conf'])
priorbox = PriorBox(img_size, 276.0, max_size=330.0, aspect_ratios=[2, 3],
                    variances=[0.1, 0.1, 0.2, 0.2],
                    name='pool6_mbox_priorbox')
net['pool6_mbox_priorbox'] = priorbox(net['pool6'])
```

I agree, that this architecture design is quite strange, because this 3x3 convolution is actually 1x1 convolution, but this is exactly the same thing that is in the original Caffe implementation. 
```
layer {
  name: "pool6_mbox_loc"
  type: "Convolution"
  bottom: "pool6"
  top: "pool6_mbox_loc"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 24
    pad: 1
    kernel_size: 3
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0.0
    }
  }
}
```
Maybe, when I finish the training part, I will try to elaborate this question and update the architecture and weights, because 1x1 convolution is faster and can help to reduce computational time a little bit. I believe, that it is not a complicated thing to do.

**Comment by lunardog** [comment]
Thank you, @rykov8 for your help. That was it. It works perfectly now.

I'm using keras v 1.1.1 with `tensorflow-0.11.0rc2` as backend.

**Comment by rykov8** [comment]
@lunardog you are welcome! Quite strange, that you have such an error, because my setup is the same. Nevertheless, thanks for pointing this out, I'd better fix this issue in further commits.
