### ISSUE TITLE
.pkl files are written for Python 3 only

### ISSUE THREAD

**Issue by ahrnbom** [rykov8/ssd_keras#3]
After messing around a bit, I was able to convert prior_boxes_ssd300.pkl to a Python2 compatible format. I'm submitting it here in case it is useful for anybody.
[prior_boxes_ssd300_python2.pkl.zip](https://github.com/rykov8/ssd_keras/files/606235/prior_boxes_ssd300_python2.pkl.zip)

The problem with the .pkl files included in this repo is that they use Pickle Protocol 3, which is only supported on Python3, not Python2. Everything else seems to work with Python2, so it's unfortunate to leave Python2 out just because of that.

I also want to take the time to thank you for porting SSD to Keras! It makes it much easier to work with, compared to the original Caffe implementation.

**Comment by rykov8** [comment]
@ahrnbom thanks for remark! I always forget about backward compatibility, I'll try to replace the files with further commits.

Nevertheless, you can obtain prior boxes with one forward pass, because priors are always the same for pictures (see `ssd.py` for reference). Here I provide this file for convenience in order to show, how to assign ground truth boxes to priors, so, even if the file is broken, I hope, that it is still possible to play with SSD.

**Comment by fortunto2** [comment]
@ahrnbom great thanks! for python2 pkl
