### ISSUE TITLE
BBoxUtility cannot NMS ground truth?

### ISSUE THREAD

**Issue by ahrnbom** [rykov8/ssd_keras#34]
Hi! I recently noticed that the detection_out method on BBoxUtility doesn't seem to work with actual ground truth data, as far as I can tell. I believe it works on output that I have gotten from the SSD network, but it seems strange that it wouldn't support the actual grount truth; if the network was trained to perfection, its output should match that of the ground truth, in theory (at least for some dataset).

The reason I care about this is because in my application, I want to debug my generator class, similar to the generator in SSD_training.ipynb. I want to run the generator and visualize its output. That should always be a good idea to make sure you're training the network on reasonable data. I can do that easily with the image data I'm feeding the network, but for the ground truth I have found no way to visualize it. The most obvious way would be to do like you'd visualize the network's output similar to how it's done in SSD_training.ipynb, by running it through detection_out and then interpreting the output visually. However, detection_out doesn't seem to produce anything reasonable when fed ground truth data.

Here's some sample code that show what I mean:

```
from ssd_utils import BBoxUtility
import pickle
import numpy as np

NUM_CLASSES = 4

priors = pickle.load(open('prior_boxes_ssd300.pkl', 'rb'))
bbox_util = BBoxUtility(NUM_CLASSES, priors)

gt_pascal = pickle.load(open('gt_pascal.pkl', 'rb'))
gt = gt_pascal[u'frame03196.png']

y = bbox_util.assign_boxes(gt)

print(y.shape)

# Visualization of y
#import cv2
#cv2.imshow("Y", y.reshape((7308/12,16*12)).transpose())
#cv2.waitKey(0)

gt2 = bbox_util.detection_out(y.reshape(1,7308,16))

print(gt)
print(gt2) 
# Why are there no coordinates here?? class numbers and confidence seem okay
# but nowhere are actual coordinates of any box.
```
I've tried this with several different ground truth arrays, both from gt_pascal.pkl and also things I've constructed on my own. Always I get garbage positions of these boxes, with xmin = 1 and xmax  = 0. As far as I can tell the class numbers and confidence (should always be 1 for the relevant boxes) seem fine, it's the coordinates that get messed up somehow.

Am I missing something, or is this a bug in BBoxUtility?

**Comment by rykov8** [comment]
@ahrnbom hi! No, there is no bug in `BBoxUtility`. If you read the docstring for `assign_boxes`, you'll find, that it returns a tensor of shape `(num_boxes, 4 + num_classes + 8)`, but the last 7 rows are all 0 and -8 row has ones if the prior is assigned, it is done in order to match the shape of the SSD output tensor (also there is a docstring in loss about it). In SSD output tensor the last 8 rows correspond to priors' coordinates and variances and are produced by the net, and `detection_out` method relies on them. So, when you pass the result of `assign_boxes` to `detection_out` you actually use wrong priors' coordinates, that is why is doesn't produce meaningful results.
The way to deal with it is quite straightforward. Some sample code:
```python
...
y = bbox_util.assign_boxes(gt)
y[:, -8:] = priors
# assume, that in priors there are priors' coordinates, you can find them in the repo
gt2 = bbox_util.detection_out(y.reshape(1,7308,16))
...
```

**Comment by ahrnbom** [comment]
Ah, that makes perfect sense! 

(About the priors in the code, the variable name "priors" is already defined so your line works with expected output).
