### ISSUE TITLE
Q: Number of classes

### ISSUE THREAD

**Issue by NegatioN** [rykov8/ssd_keras#69]
In the 2. executed box of https://github.com/rykov8/ssd_keras/blob/master/SSD.ipynb

We see that NUM_CLASSES is set to all the` len(voc_classes) + 1`.
However in the training notebook there's no mention of a +1, neither is there in the xml data-convertion script.

What's up with that? :)

**Comment by oarriaga** [comment]
Hello @NegatioN  yes, you always include the + 1 background class for the BBoxUtility, model and the loss. It is not included in the XML parser file. In the training file it is not explicitly stated but it is also there. There are 4 classes including the background class.

This +1 happens explicitly in the BBoxUtility class since this class assigns the prior/default boxes to its corresponding class including the background, which is later on used for the positive and negative loss in the MultiboxLoss class.

**Comment by NegatioN** [comment]
@oarriaga much obliged, I really appreciate your succinct and quick responses. I had a feeling i was missing something.
This is not really mentioned in the paper, but more a part of this implementation? (or the original implementation as well?)

**Comment by oarriaga** [comment]
@NegatioN oh thank you, yes I have studied this code and the paper enough so that I could help other people.

Yes I would say this is more part of the implementation and not mentioned in the paper. However, what it is mentioned on the paper is the use of positive and negative loss which are the loss associated to the objects assigned to a class different than the background and objects assigned to the background class respectively.

**Comment by NegatioN** [comment]
Thank you for the help @oarriaga :)
